### ISSUE TITLE
INVALID INSTRUMENT NAME (missing json file?)

### ISSUE THREAD

**Issue by iancrossfield** [spacetelescope/PandExo_HST#1]
Following the example, when I enter:
`hst.load_mode_dict('wfc3 g141')`
I get the error "INVALID INSTRUMENT NAME."  It looks like a file "wfc3_input.json" is being sought -- from where can one download this?

**Comment by kevin218** [comment]
This file should be located in PandExo_HST/engine/reference/.  If the file is there, perhaps try upper case ('WFC3 G141').
