### ISSUE TITLE
HST_TExoNS installation

### ISSUE THREAD

**Issue by An1th** [spacetelescope/PandExo_HST#10]
Unable to find HST_TExoNS. How to install it?

**Comment by kevin218** [comment]
I suggest using the latest version, which has moved to https://github.com/natashabatalha/PandExo. There is also an online version available through the ExoCTK website, but that appears to be down.

**Comment by sosey** [comment]
We're working on getting the website back up. @kevin218 is pandexo_hst fully deprecated by Natasha's fork?

**Comment by kevin218** [comment]
Yes, @sosey

**Comment by An1th** [comment]
Hi Kevin, 
Thanks for your suggestion.
