### ISSUE TITLE
Model spectrum does not write to text file

### ISSUE THREAD

**Issue by ernewton** [spacetelescope/PandExo_HST#3]
Apologies! I didn't mean to hit enter.

**Comment by kevin218** [comment]
I like the kind of issues that resolve themselves!

**Comment by kevin218** [comment]
exo_dict['planet']['exopath'] points to a user-supplied file.  In other words, you will need to generate your own model spectrum for plotting purposes.  ExoTransmit is good place to start for transmission spectra.


________________________________
