### ISSUE TITLE
Units documentation

### ISSUE THREAD

**Issue by ernewton** [spacetelescope/PandExo_HST#4]
Are the units on exo_dict['planet']['depth'] the same as that supplied in exo_dict['planet']['f_unit']? (I believe the answer is no, and that f_unit provides the flux unit for the user-supplied model).

How is exo_dict['observation']['norbits'] used in the precision calculation? If N=4, is that three out-of-transit orbits and 1 in-transit orbit (as plotted in step 5)?

**Comment by kevin218** [comment]
'f_unit' is not currently used in this light version of PandExo_HST.  In the full version (https://github.com/natashabatalha/PandExo/wiki), it's used to determine whether the event is a transit or an eclipse.

When not provided by the user, PandExo_HST will determine the number of HST orbits needed for a transit/eclipse observation. It will estimate the number of data points within the transit/eclipse based on the duration.  Here are two common examples:
1) For a transit duration between 0.5 and 1.5 HST orbits (48 - 144 minutes), the code assumes one orbit centered on the mid-transit time.  
2) Between 1.5 and 2.0 HST orbits, the code assumes one orbit occurs during full transit and the other orbit during ingress/egress.

The number of data points in and out of transit are used to determine the in- and out-of-transit precisions, which are then added in quadrature to predict the depth uncertainty.  The first HST orbit is never used in the calculation.

**Comment by ernewton** [comment]
Re: HST orbits -- That is awesome! Thanks.
